global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'storefront'
    static_configs:
      - targets: ['host.docker.internal:3000']
    metrics_path: '/api/metrics'

  - job_name: 'bff'
    static_configs:
      - targets: ['host.docker.internal:4000']
    metrics_path: '/api/v1/metrics'

  - job_name: 'catalog-service'
    static_configs:
      - targets: ['host.docker.internal:5001']
    metrics_path: '/api/v1/metrics'

  - job_name: 'order-service'
    static_configs:
      - targets: ['host.docker.internal:5002']
    metrics_path: '/api/v1/metrics'

  - job_name: 'payment-service'
    static_configs:
      - targets: ['host.docker.internal:5003']
    metrics_path: '/api/v1/metrics'

  - job_name: 'email-service'
    static_configs:
      - targets: ['host.docker.internal:5004']
    metrics_path: '/api/v1/metrics'

  - job_name: 'shipping-service'
    static_configs:
      - targets: ['host.docker.internal:5005']
    metrics_path: '/api/v1/metrics'

  - job_name: 'review-service'
    static_configs:
      - targets: ['host.docker.internal:5006']
    metrics_path: '/api/v1/metrics'

  - job_name: 'loyalty-service'
    static_configs:
      - targets: ['host.docker.internal:5007']
    metrics_path: '/api/v1/metrics'

  - job_name: 'search-service'
    static_configs:
      - targets: ['host.docker.internal:5008']
    metrics_path: '/api/v1/metrics'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']